# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datadisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1364, 1056)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 226, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_contract = QtWidgets.QLabel(self.layoutWidget)
        self.label_contract.setObjectName("label_contract")
        self.horizontalLayout.addWidget(self.label_contract)
        self.comboBox_contract = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_contract.setObjectName("comboBox_contract")
        self.comboBox_contract.addItem("")
        self.comboBox_contract.addItem("")
        self.comboBox_contract.addItem("")
        self.comboBox_contract.addItem("")
        self.comboBox_contract.addItem("")
        self.comboBox_contract.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_contract)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 99, 1291, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_kline = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_kline.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_kline.setObjectName("verticalLayout_kline")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1364, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_contract.setText(_translate("MainWindow", "金融期货合约："))
        self.comboBox_contract.setItemText(0, _translate("MainWindow", "IF2403"))
        self.comboBox_contract.setItemText(1, _translate("MainWindow", "TF2406"))
        self.comboBox_contract.setItemText(2, _translate("MainWindow", "IH2403"))
        self.comboBox_contract.setItemText(3, _translate("MainWindow", "IC2403"))
        self.comboBox_contract.setItemText(4, _translate("MainWindow", "TS2406"))
        self.comboBox_contract.setItemText(5, _translate("MainWindow", "IM2403"))
